version: '{build}'
image: Ubuntu
environment:
  MyGetApiKey:
    secure: ypmHjr7gmKfOUvyHhvStS7lQBTxNX8p6ByvlTFxfA59TOT0ytB31Eukm/1rKpCJK
  NugetApiKey:
    secure: todo
  
skip_branch_with_pr: true
pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - main

build_script:
  - ps: ./build.ps1

test: off

deploy_script:
  - ps: ./build.ps1 Pack
  #- ps: ./build.ps1 Push --NugetApiUrl "https://www.myget.org/F/oysteinbruin-myget/api/v2" --NugetApiKey $env:MyGetApiKey
  #- ps: |
  #    if ($env:APPVEYOR_REPO_TAG  -eq "true"){
  #        ./build.ps1 Push --NugetApiUrl "https://api.nuget.org/v3/index.json" --NugetApiKey $env:NugetApiKey
  #    }
